name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: setup cpp
      run: |
       sudo apt-get update
       sudo apt-get install cmake g++ libgtest-dev make libssl-dev
       sudo apt-get install redis valgrind
    - uses: actions/checkout@v3
    - name: CMake
      run: cmake -B build
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
